// claude-meta.test.mjs — Claude Code isMeta 记录与 step.model（纯转换层，无宿主依赖）
//
// isMeta 契约（见 lib/convert/claude.mjs 文件头）：isMeta:true 的 user 记录不是人类提问，
// 永不开新轮、不参与标题；内容不丢弃，文本缓冲到下一个 assistant 步骤 content 开头，
// 数组里同带的 tool_result 照常按 tool_use_id 配对。fixtures 全部合成。
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { convertClaudeJsonl } from '../lib/convert/index.mjs'

const SID = 'sess-meta-001'

// 源记录 → JSONL 文本（保留 sessionId；字段顺序无关）
const jsonl = (recs) => recs.map((r) => JSON.stringify({ sessionId: SID, ...r })).join('\n')

// 真实提问：字符串 content（旧格式）与文本块数组 content（新版）两种形态都要覆盖
const user = (content, extra = {}) => ({ type: 'user', message: { role: 'user', content }, ...extra })
// isMeta 记录：宿主写进转录的非提问内容
const meta = (content) => user(content, { isMeta: true })
// assistant 记录：block 数组 + 可选 model（step.model 的来源）
const asst = (blocks, model) => ({
  type: 'assistant',
  message: { role: 'assistant', ...(model ? { model } : {}), content: blocks },
})

const assistantEvents = (out) => out.events.filter((e) => e.type === 'assistant/message')
const userEvents = (out) => out.events.filter((e) => e.type === 'user/message')

// ── 1. 提问 → isMeta → assistant：不开轮，meta 前置到该步 content 开头 ──
test('claude isMeta: 提问后夹入 isMeta 记录 → 不开新轮，文本前置到下一个 assistant 步骤开头', () => {
  const out = convertClaudeJsonl(jsonl([
    user('请继续'),
    asst([{ type: 'text', text: '正在处理。' }]),
    meta('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>'),
    asst([{ type: 'text', text: '处理完成。' }]),
  ]), { fileStem: SID })

  assert.equal(out.turns.length, 1, 'isMeta 不开新轮')
  assert.equal(out.turns[0].steps.length, 2)
  // 第 1 步不受后续 meta 影响
  assert.deepEqual(out.turns[0].steps[0].content, [{ type: 'text', text: '正在处理。' }])
  // 第 2 步开头是 meta 文本（时间顺序忠实：meta 出现在该 assistant 之前）
  assert.deepEqual(out.turns[0].steps[1].content, [
    { type: 'text', text: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>' },
    { type: 'text', text: '处理完成。' },
  ])

  // 事件层：meta 不产生独立 user/message（只有环境声明 + 真实提问 + 工具结果才进 user/message）
  const assistantMsgs = assistantEvents(out)
  assert.equal(assistantMsgs.length, 2)
  assert.equal(assistantMsgs[1].data.message.content[0].text, '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>')
  assert.equal(assistantMsgs[1].data.message.content[1].text, '处理完成。')
  // user/message 的 data 直接就是消息（role/content/source），无 message 包装层
  for (const ev of userEvents(out)) {
    const texts = (Array.isArray(ev.data.content) ? ev.data.content : [])
      .filter((b) => b && b.type === 'text')
      .map((b) => b.text)
    assert.ok(!texts.some((t) => t.includes('local-command-caveat')), 'meta 正文必须搭在 assistant content 内部，不得单独成消息')
  }
  assert.equal(out.metaMessages, 1)
})

// ── 2. Skill tool_use → tool_result → isMeta(sourceToolUseID) → assistant 续写 ──
test('claude isMeta: 工具结果之后的 meta 不切断轮、不破坏配对', () => {
  const out = convertClaudeJsonl(jsonl([
    user('帮我用 skill 部署'),
    asst([
      { type: 'text', text: '先加载 skill。' },
      { type: 'tool_use', id: 'toolu_skill', name: 'Skill', input: { skill: 'deploy' } },
    ]),
    user([{ type: 'tool_result', tool_use_id: 'toolu_skill', content: [{ type: 'text', text: 'skill 已加载' }] }]),
    meta([{ type: 'text', text: 'Base directory for this skill: D:\\demo\\skills\\deploy', sourceToolUseID: 'toolu_skill' }]),
    asst([{ type: 'text', text: '按 skill 步骤执行完成。' }]),
  ]), { fileStem: SID })

  assert.equal(out.turns.length, 1, 'meta 不切断轮')
  assert.equal(out.turns[0].steps.length, 2)
  const step2 = out.turns[0].steps[1]
  assert.equal(step2.content[0].text, 'Base directory for this skill: D:\\demo\\skills\\deploy')
  assert.equal(step2.content[0].type, 'text')

  // 配对：tool/call 与其 tool/result 一一对应，sourceEventSeqs 指向调用
  const calls = out.events.filter((e) => e.type === 'tool/call')
  const results = out.events.filter((e) => e.type === 'tool/result')
  assert.equal(calls.length, 1)
  assert.equal(results.length, 1)
  assert.equal(results[0].data.message.content[0].toolCallId, 'toolu_skill')
  assert.deepEqual(results[0].sourceEventSeqs, [calls[0].seq])
  assert.equal(results[0].data.message.content[0].content[0].text, 'skill 已加载')

  // meta 未在 tool 消息之前插入独立 user 消息（wire 规则：tool_calls 与 tool 消息之间
  // 不允许出现别的消息）
  assert.equal(out.metaMessages, 1)
})

// ── 2b. meta 出现在 tool_result 之前（真实转录里两者都在 assistant 之后，顺序不定） ──
test('claude isMeta: meta 先到、tool_result 后到 → 轮数与配对均不受影响', () => {
  const out = convertClaudeJsonl(jsonl([
    user('跑一下'),
    asst([{ type: 'tool_use', id: 'toolu_a', name: 'Bash', input: { command: 'ls' } }]),
    meta('<local-command-caveat>caveat</local-command-caveat>'),
    user([{ type: 'tool_result', tool_use_id: 'toolu_a', content: [{ type: 'text', text: 'a.txt' }] }]),
    asst([{ type: 'text', text: '看到 a.txt。' }]),
  ]), { fileStem: SID })

  assert.equal(out.turns.length, 1)
  assert.equal(out.turns[0].steps.length, 2)
  assert.equal(out.turns[0].steps[1].content[0].text, '<local-command-caveat>caveat</local-command-caveat>')
  const results = out.events.filter((e) => e.type === 'tool/result')
  assert.equal(results.length, 1)
  assert.equal(results[0].data.message.content[0].content[0].text, 'a.txt')
  assert.equal(out.metaMessages, 1)
})

// ── 3. 文件开头 isMeta（任何真实提问之前）→ 无空 prompt 假轮 ──
test('claude isMeta: 真实提问之前的 isMeta 只缓冲，不产生空 prompt 假轮', () => {
  const out = convertClaudeJsonl(jsonl([
    meta('<local-command-caveat>Caveat: 本地命令输出</local-command-caveat>'),
    user('真实提问'),
    asst([{ type: 'text', text: '回答。' }]),
  ]), { fileStem: SID })

  assert.equal(out.turns.length, 1, '只有一条真实提问 = 一轮')
  assert.equal(out.turns[0].prompt, '真实提问')
  assert.deepEqual(out.turns.map((t) => t.prompt), ['真实提问'])
  // 首个 assistant 步骤前置了文件开头的 meta
  assert.deepEqual(out.turns[0].steps[0].content, [
    { type: 'text', text: '<local-command-caveat>Caveat: 本地命令输出</local-command-caveat>' },
    { type: 'text', text: '回答。' },
  ])
  // 标题取真实提问，不是 meta 正文（meta 不参与标题）
  assert.equal(out.title, '真实提问')
  assert.equal(out.events.some((e) => e.type === 'session/title'), false)
  assert.equal(out.metaMessages, 1)
})

// ── 3b. 整份转录只有 isMeta（无真实提问）→ 0 轮、丢弃但不崩 ──
test('claude isMeta: 只有 isMeta 的转录 → 0 轮，不新增空 prompt 假轮', () => {
  const out = convertClaudeJsonl(jsonl([
    meta('[Image: source: D:\\demo\\shot.png]'),
    meta('Continue from where you left off.'),
  ]), { fileStem: SID })

  assert.equal(out.turns.length, 0)
  assert.equal(out.metaMessages, 2)
  assert.equal(out.events.some((e) => e.type === 'turn/start'), false)
  assert.equal(out.skipReason, undefined, 'isMeta 不是无法解析的 user 消息，不报内容丢失')
  assert.equal(out.droppedUserPrompts, 0)
})

// ── 4. 压缩摘要 → isMeta → 下一提问：检查点语义不变 ──
test('claude isMeta: 压缩检查点之后的 isMeta 不改变检查点与轮结构', () => {
  const summary = 'This session is being continued from a previous conversation that ran out of context.\n\nSummary:\n1. 要点'
  const out = convertClaudeJsonl(jsonl([
    user('问题1'),
    asst([{ type: 'text', text: '回答1' }]),
    { type: 'system', subtype: 'compact_boundary', content: 'Conversation compacted' },
    user(summary, { isCompactSummary: true }),
    user('问题2'),
    asst([{ type: 'text', text: '回答2' }]),
  ]), { fileStem: SID })

  assert.equal(out.compacted, true)
  assert.equal(out.compactions, 1)
  assert.equal(out.turns.length, 2)
  assert.deepEqual(out.turns.map((t) => t.prompt), ['问题1', '问题2'])
  const summaries = out.events.filter((e) => e.type === 'compaction/summary')
  assert.equal(summaries.length, 1)
  assert.equal(summaries[0].data.summary[0].text, summary)
  // 压缩边界之后没有 isMeta 时，第 2 步只有回答正文（回归：检查点后行为不变）
  assert.deepEqual(out.turns[1].steps[0].content, [{ type: 'text', text: '回答2' }])
  assert.equal(out.metaMessages, undefined, '无 isMeta 时不占 metaMessages 键')

  // 同一形状 + 压缩点后的 isMeta：检查点数量/摘要不变，isMeta 只前置到下一步
  const withMeta = convertClaudeJsonl(jsonl([
    user('问题1'),
    asst([{ type: 'text', text: '回答1' }]),
    { type: 'system', subtype: 'compact_boundary', content: 'Conversation compacted' },
    user(summary, { isCompactSummary: true }),
    meta('Continue from where you left off.'),
    user('问题2'),
    asst([{ type: 'text', text: '回答2' }]),
  ]), { fileStem: SID })
  assert.equal(withMeta.compactions, 1)
  assert.equal(withMeta.turns.length, 2)
  assert.deepEqual(withMeta.turns.map((t) => t.prompt), ['问题1', '问题2'])
  assert.deepEqual(withMeta.turns[1].steps[0].content, [
    { type: 'text', text: 'Continue from where you left off.' },
    { type: 'text', text: '回答2' },
  ])
  assert.equal(withMeta.metaMessages, 1)
})

// ── 5. isMeta 记录内含 tool_result 块：结果照常配对，剩余文本进 pendingMeta ──
test('claude isMeta: meta 记录里的 tool_result 照常配对，同一记录的文本仍前置', () => {
  const out = convertClaudeJsonl(jsonl([
    user('加载 skill'),
    asst([{ type: 'tool_use', id: 'toolu_m', name: 'Skill', input: { skill: 'x' } }]),
    meta([
      { type: 'tool_result', tool_use_id: 'toolu_m', content: [{ type: 'text', text: 'SKILL BODY' }] },
      { type: 'text', text: 'Base directory for this skill: D:\\demo\\skills\\x' },
    ]),
    asst([{ type: 'text', text: '继续。' }]),
  ]), { fileStem: SID })

  assert.equal(out.turns.length, 1, 'meta 里的 tool_result 不开新轮')
  // 结果没有丢：挂回调用所在步
  const results = out.events.filter((e) => e.type === 'tool/result')
  assert.equal(results.length, 1)
  assert.equal(results[0].data.message.content[0].content[0].text, 'SKILL BODY')
  // 同记录的文本进 pendingMeta → 前置到下一步
  assert.deepEqual(out.turns[0].steps[1].content, [
    { type: 'text', text: 'Base directory for this skill: D:\\demo\\skills\\x' },
    { type: 'text', text: '继续。' },
  ])
  // 承载 tool_result 的 meta 记录本身不成为提问：user/message 只有真实提问与环境声明
  const prompts = userEvents(out)
    .filter((e) => (e.data.source || {}).kind === 'user')
    .map((e) => e.data.content[0].text)
  assert.deepEqual(prompts, ['加载 skill'])
  assert.equal(out.metaMessages, 1)
})

// ── 5b. 多条 isMeta 按时间顺序追加；会话结束的残余 meta 追加到最后一步末尾 ──
test('claude isMeta: 多条 meta 按序合并，会话结束的残余追加到最后一步 content 末尾', () => {
  const out = convertClaudeJsonl(jsonl([
    user('开始'),
    asst([{ type: 'text', text: '好。' }]),
    meta('第一条 meta'),
    meta('第二条 meta'),
    asst([{ type: 'text', text: '收到。' }]),
    meta('尾部残余 meta'),
  ]), { fileStem: SID })

  assert.equal(out.turns.length, 1)
  // 两条 meta 合并前置到第 2 步（步骤数不变：不因 meta 拆步）
  assert.deepEqual(out.turns[0].steps.map((s) => s.content[0].text), ['好。', '第一条 meta\n第二条 meta'])
  assert.equal(out.turns[0].steps.length, 2)
  // 残余 meta 追加到最后一步 content 末尾（不建新步、不建新轮）
  assert.deepEqual(out.turns[0].steps[1].content, [
    { type: 'text', text: '第一条 meta\n第二条 meta' },
    { type: 'text', text: '收到。' },
    { type: 'text', text: '尾部残余 meta' },
  ])
  assert.equal(out.metaMessages, 3)
})

// ── 5c. 会话结束残余 meta 且当前轮无步骤 → 丢弃（不补假步/假轮） ──
test('claude isMeta: 无步骤承载的残余 meta 丢弃，不为它补空 prompt 假轮', () => {
  const out = convertClaudeJsonl(jsonl([
    user('还没等到回答'),
    meta('[Your previous response had no visible output]'),
  ]), { fileStem: SID })

  assert.equal(out.turns.length, 1)
  assert.equal(out.turns[0].steps.length, 0, '不补空步骤承载残余 meta')
  assert.deepEqual(out.turns[0].prompt, '还没等到回答')
  assert.equal(out.metaMessages, 1)
})

// ── 6. metaMessages 计数（失败要大声） ──
test('claude isMeta: metaMessages 计数识别到的 isMeta 记录数', () => {
  const out = convertClaudeJsonl(jsonl([
    user('提问'),
    asst([{ type: 'text', text: '回答' }]),
    meta('meta-1'),
    meta([{ type: 'text', text: 'meta-2' }, { type: 'text', text: 'meta-3' }]),
    // 结构块（无 text）：仍算一条 isMeta 记录，但没有文本可前置
    meta([{ type: 'image', source: { type: 'base64', media_type: 'image/png', data: 'AAAA' } }]),
    // content 形态怪异（对象）：同样不得变成空 prompt 假轮
    meta({ unexpected: true }),
  ]), { fileStem: SID })

  assert.equal(out.turns.length, 1, '4 条 isMeta 记录都不得开新轮')
  assert.equal(out.metaMessages, 4)
  assert.equal(out.turns[0].steps.length, 1, 'meta 不拆步')
  // 有文本的三条合并成一块追加到当前轮最后一步末尾；结构块（image）无文本可留
  assert.deepEqual(out.turns[0].steps[0].content, [
    { type: 'text', text: '回答' },
    { type: 'text', text: 'meta-1\nmeta-2\nmeta-3' },
  ])
  assert.equal(out.droppedUserPrompts, 0, 'isMeta 记录不计入无法解析的 user 消息')
})

// ── 6b. 辅助 transcript 早退形状同样带 metaMessages ──
test('claude isMeta: 辅助 transcript 早退返回保留 metaMessages 键', () => {
  const out = convertClaudeJsonl(jsonl([
    meta('skill 正文'),
    user('子任务提问'),
  ]), { fileStem: 'agent-other' })
  assert.equal(out.meta, null)
  assert.equal(out.metaMessages, 0)
  assert.match(out.skipReason, /auxiliary transcript/)
})

// ── 7. 中途切 model：各步带各 step.model，会话级 model 取第一条兜底 ──
test('claude step.model: 各 assistant 步骤记录自己的 model，会话级 model 取第一条', () => {
  const out = convertClaudeJsonl(jsonl([
    user('问题1'),
    asst([{ type: 'text', text: '答1' }], 'claude-sonnet-4-5'),
    user('问题2'),
    asst([{ type: 'text', text: '答2' }], 'claude-opus-4-7'),
    // 无 model 字段的 assistant：不写 step.model，回落会话级 model
    asst([{ type: 'text', text: '答3' }]),
  ]), { fileStem: SID })

  assert.equal(out.turns.length, 2)
  assert.deepEqual(out.turns[0].steps.map((s) => s.model), ['claude-sonnet-4-5'])
  assert.deepEqual(out.turns[1].steps.map((s) => s.model), ['claude-opus-4-7', undefined])
  const sources = assistantEvents(out).map((e) => e.data.message.source.model)
  assert.deepEqual(sources, ['claude-sonnet-4-5', 'claude-opus-4-7', 'claude-sonnet-4-5'])
})

// ── 7b. isMeta 之后切的 model：meta 前置不改变 step.model ──
test('claude step.model: isMeta 前置到带新 model 的步骤后，该步仍记自己的 model', () => {
  const out = convertClaudeJsonl(jsonl([
    user('问题'),
    asst([{ type: 'text', text: '答1' }], 'claude-sonnet-4-5'),
    meta('Continue from where you left off.'),
    asst([{ type: 'text', text: '答2' }], 'claude-opus-4-7'),
  ]), { fileStem: SID })

  assert.deepEqual(out.turns[0].steps.map((s) => s.model), ['claude-sonnet-4-5', 'claude-opus-4-7'])
  assert.deepEqual(out.turns[0].steps[1].content, [
    { type: 'text', text: 'Continue from where you left off.' },
    { type: 'text', text: '答2' },
  ])
  assert.equal(assistantEvents(out)[1].data.message.source.model, 'claude-opus-4-7')
})

// ── 8. firstTopicPrompt 行为不变（注入块与粘贴信封口径照旧） ──
test('claude isMeta: firstTopicPrompt 行为不变（跳过注入块取首个真实提问；粘贴信封剥离正文）', () => {
  // 注入块（此处为 isMeta：不是提问、不作标题）、斜杠命令日志之后的真实提问才是话题
  const injected = convertClaudeJsonl(jsonl([
    meta('<local-command-caveat>Caveat: 本地命令输出</local-command-caveat>'),
    user('<command-name>/model</command-name> <command-message>model</command-message>'),
    user('继续处理'),
    asst([{ type: 'text', text: '好。' }]),
  ]), { fileStem: SID })
  assert.equal(injected.title, '继续处理')
  assert.equal(injected.turns.length, 2, '斜杠命令日志仍按既有行为开轮（只是不作标题），isMeta 不开轮')

  // 粘贴信封剥离后作标题
  const pasted = convertClaudeJsonl(jsonl([
    user('<pasted_content id="1b70">\n首页改成下面的样子：1. …\n</pasted_content>'),
    asst([{ type: 'text', text: '好。' }]),
  ]), { fileStem: SID })
  assert.equal(pasted.title, '首页改成下面的样子：1. …')

  // 全是注入块 → 无话题（不钉标题）
  const onlyInjected = convertClaudeJsonl(jsonl([
    user('<local-command-caveat>Caveat: 只有本地命令</local-command-caveat>'),
    asst([{ type: 'text', text: '好。' }]),
  ]), { fileStem: SID })
  assert.equal(onlyInjected.title, '')
  assert.equal(onlyInjected.events.some((e) => e.type === 'session/title'), false)
})
